# Generated by Django 2.2.7 on 2019-11-23 19:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Issue',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('issue_number', models.IntegerField()),
                ('state', models.CharField(max_length=20)),
                ('author', models.CharField(max_length=50)),
                ('date', models.DateTimeField()),
            ],
        ),
    ]
