# Generated by Django 2.2.7 on 2019-11-23 21:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('repositories', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Commit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sha_commit', models.CharField(max_length=60)),
                ('author', models.CharField(max_length=50)),
                ('date', models.DateTimeField()),
                ('repository', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='repositories.Repository')),
            ],
        ),
    ]
