# Generated by Django 2.2.7 on 2019-11-27 00:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('milestone', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='milestone',
            old_name='milestoneID',
            new_name='milestone_number',
        ),
    ]
